version: '3.9'

services:
  db:
    container_name: db
    image: postgress
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $PORT_DATA:$PORT_DATA
    
  server:
    container_name: server
    build: .
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
      - PORT=$PORT
      - JWT=$JWT
      - MY_PASS=$MY_PASS
      - MY_HOST=$MY_HOST
      - MY_MAIL=$MY_MAIL
    ports:
      - $PORT:$PORT
    depends_on:
      - db